<?php
//if( function_exists('acf_add_local_field_group') ):
//
//acf_add_local_field_group(array(
//	'key' => 'group_5e72fbf595313',
//	'title' => 'Doctors Informations',
//	'fields' => array(
//		array(
//			'key' => 'field_5e72fc548aa17',
//			'label' => 'Phone',
//			'name' => 'phone',
//			'type' => 'text',
//			'instructions' => '',
//			'required' => 0,
//			'conditional_logic' => 0,
//			'wrapper' => array(
//				'width' => '',
//				'class' => '',
//				'id' => '',
//			),
//			'default_value' => '',
//			'placeholder' => '',
//			'prepend' => '',
//			'append' => '',
//			'maxlength' => '',
//		),
//		array(
//			'key' => 'field_5e72fc628aa18',
//			'label' => 'Email',
//			'name' => 'email',
//			'type' => 'email',
//			'instructions' => '',
//			'required' => 0,
//			'conditional_logic' => 0,
//			'wrapper' => array(
//				'width' => '',
//				'class' => '',
//				'id' => '',
//			),
//			'default_value' => '',
//			'placeholder' => '',
//			'prepend' => '',
//			'append' => '',
//		),
//		array(
//			'key' => 'field_5e72fc758aa19',
//			'label' => 'Specialization',
//			'name' => 'specialization',
//			'type' => 'text',
//			'instructions' => '',
//			'required' => 0,
//			'conditional_logic' => 0,
//			'wrapper' => array(
//				'width' => '',
//				'class' => '',
//				'id' => '',
//			),
//			'default_value' => '',
//			'placeholder' => '',
//			'prepend' => '',
//			'append' => '',
//			'maxlength' => '',
//		),
//		array(
//			'key' => 'field_5e72fc894be77',
//			'label' => 'First Name',
//			'name' => 'first_name',
//			'type' => 'text',
//			'instructions' => '',
//			'required' => 0,
//			'conditional_logic' => 0,
//			'wrapper' => array(
//				'width' => '',
//				'class' => '',
//				'id' => '',
//			),
//			'default_value' => '',
//			'placeholder' => '',
//			'prepend' => '',
//			'append' => '',
//			'maxlength' => '',
//		),
//		array(
//			'key' => 'field_5e72fc904be78',
//			'label' => 'Last Name',
//			'name' => 'last_name',
//			'type' => 'text',
//			'instructions' => '',
//			'required' => 0,
//			'conditional_logic' => 0,
//			'wrapper' => array(
//				'width' => '',
//				'class' => '',
//				'id' => '',
//			),
//			'default_value' => '',
//			'placeholder' => '',
//			'prepend' => '',
//			'append' => '',
//			'maxlength' => '',
//		),
//	),
//	'location' => array(
//		array(
//			array(
//				'param' => 'post_type',
//				'operator' => '==',
//				'value' => 'doctor',
//			),
//		),
//	),
//	'menu_order' => 0,
//	'position' => 'normal',
//	'style' => 'default',
//	'label_placement' => 'top',
//	'instruction_placement' => 'label',
//	'hide_on_screen' => '',
//	'active' => true,
//	'description' => '',
//));
//
//acf_add_local_field_group(array(
//	'key' => 'group_5e719f9727120',
//	'title' => 'Filterable Gallery',
//	'fields' => array(
//		array(
//			'key' => 'field_5e72e721a61e7',
//			'label' => 'Basic Information',
//			'name' => '',
//			'type' => 'tab',
//			'instructions' => '',
//			'required' => 0,
//			'conditional_logic' => 0,
//			'wrapper' => array(
//				'width' => '',
//				'class' => '',
//				'id' => '',
//			),
//			'placement' => 'left',
//			'endpoint' => 0,
//		),
//		array(
//			'key' => 'field_5e71b58f81799',
//			'label' => 'Case Number',
//			'name' => 'case_number',
//			'type' => 'text',
//			'instructions' => '',
//			'required' => 0,
//			'conditional_logic' => 0,
//			'wrapper' => array(
//				'width' => '',
//				'class' => '',
//				'id' => '',
//			),
//			'default_value' => '',
//			'placeholder' => '',
//			'prepend' => '',
//			'append' => '',
//			'maxlength' => '',
//		),
//		array(
//			'key' => 'field_5e72e5b1f72f1',
//			'label' => 'Doctors',
//			'name' => 'doctors',
//			'type' => 'repeater',
//			'instructions' => '',
//			'required' => 0,
//			'conditional_logic' => 0,
//			'wrapper' => array(
//				'width' => '',
//				'class' => '',
//				'id' => '',
//			),
//			'collapsed' => '',
//			'min' => 0,
//			'max' => 0,
//			'layout' => 'table',
//			'button_label' => '',
//			'sub_fields' => array(
//				array(
//					'key' => 'field_5e72eadff7366',
//					'label' => 'Doctor Name',
//					'name' => 'details',
//					'type' => 'post_object',
//					'instructions' => '',
//					'required' => 0,
//					'conditional_logic' => 0,
//					'wrapper' => array(
//						'width' => '',
//						'class' => '',
//						'id' => '',
//					),
//					'post_type' => array(
//						0 => 'doctor',
//					),
//					'taxonomy' => '',
//					'allow_null' => 0,
//					'multiple' => 0,
//					'return_format' => 'object',
//					'ui' => 1,
//				),
//			),
//		),
//		array(
//			'key' => 'field_5e7d78e0a2573',
//			'label' => 'Ethnicity',
//			'name' => 'ethnicity',
//			'type' => 'radio',
//			'instructions' => '',
//			'required' => 0,
//			'conditional_logic' => 0,
//			'wrapper' => array(
//				'width' => '',
//				'class' => '',
//				'id' => '',
//			),
//			'choices' => array(
//				'Any' => 'Any',
//				'Caucasian' => 'Caucasian',
//				'Black' => 'Black',
//				'Hispanic' => 'Hispanic',
//				'Asian' => 'Asian',
//				'Other' => 'Other',
//			),
//			'allow_null' => 0,
//			'other_choice' => 0,
//			'default_value' => '',
//			'layout' => 'vertical',
//			'return_format' => 'value',
//			'save_other_choice' => 0,
//		),
//		array(
//			'key' => 'field_5e71b5c130ff3',
//			'label' => 'Gender',
//			'name' => 'gender',
//			'type' => 'text',
//			'instructions' => '',
//			'required' => 0,
//			'conditional_logic' => 0,
//			'wrapper' => array(
//				'width' => '',
//				'class' => '',
//				'id' => '',
//			),
//			'default_value' => '',
//			'placeholder' => '',
//			'prepend' => '',
//			'append' => '',
//			'maxlength' => '',
//		),
//		array(
//			'key' => 'field_5e71b5b730ff2',
//			'label' => 'Age',
//			'name' => 'age',
//			'type' => 'text',
//			'instructions' => '',
//			'required' => 0,
//			'conditional_logic' => 0,
//			'wrapper' => array(
//				'width' => '',
//				'class' => '',
//				'id' => '',
//			),
//			'default_value' => '',
//			'placeholder' => '',
//			'prepend' => '',
//			'append' => '',
//			'maxlength' => '',
//		),
//		array(
//			'key' => 'field_5e797fd1403bc',
//			'label' => 'Description',
//			'name' => 'description',
//			'type' => 'wysiwyg',
//			'instructions' => '',
//			'required' => 0,
//			'conditional_logic' => 0,
//			'wrapper' => array(
//				'width' => '',
//				'class' => '',
//				'id' => '',
//			),
//			'default_value' => '',
//			'tabs' => 'all',
//			'toolbar' => 'full',
//			'media_upload' => 1,
//			'delay' => 0,
//		),
//		array(
//			'key' => 'field_5e72c89413c3a',
//			'label' => 'Video Area',
//			'name' => 'video_area',
//			'type' => 'group',
//			'instructions' => '',
//			'required' => 0,
//			'conditional_logic' => 0,
//			'wrapper' => array(
//				'width' => '',
//				'class' => '',
//				'id' => '',
//			),
//			'layout' => 'row',
//			'sub_fields' => array(
//				array(
//					'key' => 'field_5e7c037a22a76',
//					'label' => 'Video Poster',
//					'name' => 'poster',
//					'type' => 'image',
//					'instructions' => '',
//					'required' => 0,
//					'conditional_logic' => 0,
//					'wrapper' => array(
//						'width' => '',
//						'class' => '',
//						'id' => '',
//					),
//					'return_format' => 'array',
//					'preview_size' => 'full',
//					'library' => 'all',
//					'min_width' => '',
//					'min_height' => '',
//					'min_size' => '',
//					'max_width' => '',
//					'max_height' => '',
//					'max_size' => '',
//					'mime_types' => '',
//				),
//				array(
//					'key' => 'field_5e72c8c213c3b',
//					'label' => 'Video Url',
//					'name' => 'url',
//					'type' => 'url',
//					'instructions' => '',
//					'required' => 0,
//					'conditional_logic' => 0,
//					'wrapper' => array(
//						'width' => '',
//						'class' => '',
//						'id' => '',
//					),
//					'default_value' => '',
//					'placeholder' => '',
//				),
//				array(
//					'key' => 'field_5e7bf7530f5c8',
//					'label' => 'Video Button',
//					'name' => 'button',
//					'type' => 'group',
//					'instructions' => '',
//					'required' => 0,
//					'conditional_logic' => 0,
//					'wrapper' => array(
//						'width' => '',
//						'class' => '',
//						'id' => '',
//					),
//					'layout' => 'table',
//					'sub_fields' => array(
//						array(
//							'key' => 'field_5e7bf77d0f5c9',
//							'label' => 'Label',
//							'name' => 'label',
//							'type' => 'text',
//							'instructions' => '',
//							'required' => 0,
//							'conditional_logic' => 0,
//							'wrapper' => array(
//								'width' => '',
//								'class' => '',
//								'id' => '',
//							),
//							'default_value' => '',
//							'placeholder' => '',
//							'prepend' => '',
//							'append' => '',
//							'maxlength' => '',
//						),
//						array(
//							'key' => 'field_5e7bf7aa0f5ca',
//							'label' => 'Url',
//							'name' => 'url',
//							'type' => 'url',
//							'instructions' => '',
//							'required' => 0,
//							'conditional_logic' => 0,
//							'wrapper' => array(
//								'width' => '',
//								'class' => '',
//								'id' => '',
//							),
//							'default_value' => '',
//							'placeholder' => '',
//						),
//					),
//				),
//			),
//		),
//		array(
//			'key' => 'field_5e72c917fc947',
//			'label' => 'Case Details',
//			'name' => 'case_details',
//			'type' => 'group',
//			'instructions' => '',
//			'required' => 0,
//			'conditional_logic' => 0,
//			'wrapper' => array(
//				'width' => '',
//				'class' => '',
//				'id' => '',
//			),
//			'layout' => 'block',
//			'sub_fields' => array(
//				array(
//					'key' => 'field_5e81888639b26',
//					'label' => 'Description',
//					'name' => 'description',
//					'type' => 'wysiwyg',
//					'instructions' => '',
//					'required' => 0,
//					'conditional_logic' => 0,
//					'wrapper' => array(
//						'width' => '',
//						'class' => '',
//						'id' => '',
//					),
//					'default_value' => '',
//					'tabs' => 'all',
//					'toolbar' => 'full',
//					'media_upload' => 1,
//					'delay' => 0,
//				),
//				array(
//					'key' => 'field_5e81889839b27',
//					'label' => 'List',
//					'name' => 'list',
//					'type' => 'repeater',
//					'instructions' => '',
//					'required' => 0,
//					'conditional_logic' => 0,
//					'wrapper' => array(
//						'width' => '',
//						'class' => '',
//						'id' => '',
//					),
//					'collapsed' => '',
//					'min' => 0,
//					'max' => 0,
//					'layout' => 'table',
//					'button_label' => '',
//					'sub_fields' => array(
//						array(
//							'key' => 'field_5e8188b239b28',
//							'label' => 'Title',
//							'name' => 'title',
//							'type' => 'text',
//							'instructions' => '',
//							'required' => 0,
//							'conditional_logic' => 0,
//							'wrapper' => array(
//								'width' => '',
//								'class' => '',
//								'id' => '',
//							),
//							'default_value' => '',
//							'placeholder' => '',
//							'prepend' => '',
//							'append' => '',
//							'maxlength' => '',
//						),
//						array(
//							'key' => 'field_5e8188b939b29',
//							'label' => 'Description',
//							'name' => 'description',
//							'type' => 'textarea',
//							'instructions' => '',
//							'required' => 0,
//							'conditional_logic' => 0,
//							'wrapper' => array(
//								'width' => '',
//								'class' => '',
//								'id' => '',
//							),
//							'default_value' => '',
//							'placeholder' => '',
//							'maxlength' => '',
//							'rows' => '',
//							'new_lines' => '',
//						),
//					),
//				),
//			),
//		),
//		array(
//			'key' => 'field_5e72e75fb48c2',
//			'label' => 'Cases Images',
//			'name' => '',
//			'type' => 'tab',
//			'instructions' => '',
//			'required' => 0,
//			'conditional_logic' => 0,
//			'wrapper' => array(
//				'width' => '',
//				'class' => '',
//				'id' => '',
//			),
//			'placement' => 'top',
//			'endpoint' => 0,
//		),
//		array(
//			'key' => 'field_5e71b4282c52f',
//			'label' => 'Slideshow',
//			'name' => 'slideshow',
//			'type' => 'repeater',
//			'instructions' => '',
//			'required' => 0,
//			'conditional_logic' => 0,
//			'wrapper' => array(
//				'width' => '',
//				'class' => '',
//				'id' => '',
//			),
//			'collapsed' => '',
//			'min' => 0,
//			'max' => 0,
//			'layout' => 'table',
//			'button_label' => '',
//			'sub_fields' => array(
//				array(
//					'key' => 'field_5e71b44a2c531',
//					'label' => 'Before',
//					'name' => 'before',
//					'type' => 'group',
//					'instructions' => '',
//					'required' => 0,
//					'conditional_logic' => 0,
//					'wrapper' => array(
//						'width' => '',
//						'class' => '',
//						'id' => '',
//					),
//					'layout' => 'block',
//					'sub_fields' => array(
//						array(
//							'key' => 'field_5e71ba49a3db7',
//							'label' => 'Text Field',
//							'name' => 'text_field',
//							'type' => 'text',
//							'instructions' => '',
//							'required' => 0,
//							'conditional_logic' => 0,
//							'wrapper' => array(
//								'width' => '',
//								'class' => '',
//								'id' => '',
//							),
//							'default_value' => '',
//							'placeholder' => '',
//							'prepend' => '',
//							'append' => '',
//							'maxlength' => '',
//						),
//						array(
//							'key' => 'field_5e71b4a92c536',
//							'label' => 'Image',
//							'name' => 'image',
//							'type' => 'image',
//							'instructions' => '',
//							'required' => 0,
//							'conditional_logic' => 0,
//							'wrapper' => array(
//								'width' => '',
//								'class' => '',
//								'id' => '',
//							),
//							'return_format' => 'array',
//							'preview_size' => 'medium',
//							'library' => 'all',
//							'min_width' => '',
//							'min_height' => '',
//							'min_size' => '',
//							'max_width' => '',
//							'max_height' => '',
//							'max_size' => '',
//							'mime_types' => '',
//						),
//					),
//				),
//				array(
//					'key' => 'field_5e71b4bb2c537',
//					'label' => 'After',
//					'name' => 'after',
//					'type' => 'group',
//					'instructions' => '',
//					'required' => 0,
//					'conditional_logic' => 0,
//					'wrapper' => array(
//						'width' => '',
//						'class' => '',
//						'id' => '',
//					),
//					'layout' => 'block',
//					'sub_fields' => array(
//						array(
//							'key' => 'field_5e71b4c42c538',
//							'label' => 'Text Field',
//							'name' => 'text_field',
//							'type' => 'text',
//							'instructions' => '',
//							'required' => 0,
//							'conditional_logic' => 0,
//							'wrapper' => array(
//								'width' => '',
//								'class' => '',
//								'id' => '',
//							),
//							'default_value' => '',
//							'placeholder' => '',
//							'prepend' => '',
//							'append' => '',
//							'maxlength' => '',
//						),
//						array(
//							'key' => 'field_5e71b4c82c539',
//							'label' => 'Image',
//							'name' => 'image',
//							'type' => 'image',
//							'instructions' => '',
//							'required' => 0,
//							'conditional_logic' => 0,
//							'wrapper' => array(
//								'width' => '',
//								'class' => '',
//								'id' => '',
//							),
//							'return_format' => 'array',
//							'preview_size' => 'medium',
//							'library' => 'all',
//							'min_width' => '',
//							'min_height' => '',
//							'min_size' => '',
//							'max_width' => '',
//							'max_height' => '',
//							'max_size' => '',
//							'mime_types' => '',
//						),
//					),
//				),
//			),
//		),
//		array(
//			'key' => 'field_5e72e778b48c3',
//			'label' => 'Procedures',
//			'name' => '',
//			'type' => 'tab',
//			'instructions' => '',
//			'required' => 0,
//			'conditional_logic' => 0,
//			'wrapper' => array(
//				'width' => '',
//				'class' => '',
//				'id' => '',
//			),
//			'placement' => 'top',
//			'endpoint' => 0,
//		),
//		array(
//			'key' => 'field_5e71b5d030ff4',
//			'label' => 'Procedure',
//			'name' => 'procedure_types',
//			'type' => 'select',
//			'instructions' => '',
//			'required' => 0,
//			'conditional_logic' => 0,
//			'wrapper' => array(
//				'width' => '',
//				'class' => '',
//				'id' => '',
//			),
//			'choices' => array(
//				'Rhinoplasty' => 'Rhinoplasty',
//				'Face' => 'Face',
//				'Liposuction' => 'Liposuction',
//				'Breast Augmentation' => 'Breast Augmentation',
//			),
//			'default_value' => array(
//			),
//			'allow_null' => 0,
//			'multiple' => 0,
//			'ui' => 0,
//			'return_format' => 'value',
//			'ajax' => 0,
//			'placeholder' => '',
//		),
//		array(
//			'key' => 'field_5e7d701050d3c',
//			'label' => 'Implant type',
//			'name' => 'rhinoplasty_implant_type',
//			'type' => 'radio',
//			'instructions' => '',
//			'required' => 0,
//			'conditional_logic' => array(
//				array(
//					array(
//						'field' => 'field_5e71b5d030ff4',
//						'operator' => '==',
//						'value' => 'Rhinoplasty',
//					),
//				),
//			),
//			'wrapper' => array(
//				'width' => '',
//				'class' => '',
//				'id' => '',
//			),
//			'choices' => array(
//				'Silicon' => 'Silicon',
//				'Gore-Tex' => 'Gore-Tex',
//				'Sili-Tex' => 'Sili-Tex',
//			),
//			'allow_null' => 0,
//			'other_choice' => 0,
//			'default_value' => '',
//			'layout' => 'vertical',
//			'return_format' => 'value',
//			'save_other_choice' => 0,
//		),
//		array(
//			'key' => 'field_5e7d7077cf0bd',
//			'label' => 'Procedure Type',
//			'name' => 'face_procedure_type',
//			'type' => 'radio',
//			'instructions' => '',
//			'required' => 0,
//			'conditional_logic' => array(
//				array(
//					array(
//						'field' => 'field_5e71b5d030ff4',
//						'operator' => '==',
//						'value' => 'Face',
//					),
//				),
//			),
//			'wrapper' => array(
//				'width' => '',
//				'class' => '',
//				'id' => '',
//			),
//			'choices' => array(
//				'Face sculpt' => 'Face sculpt',
//				'Botox' => 'Botox',
//				'Dermatological Treatment' => 'Dermatological Treatment',
//			),
//			'allow_null' => 0,
//			'other_choice' => 0,
//			'default_value' => '',
//			'layout' => 'vertical',
//			'return_format' => 'value',
//			'save_other_choice' => 0,
//		),
//		array(
//			'key' => 'field_5e7d70fe33a3e',
//			'label' => 'Area',
//			'name' => 'liposuction_area',
//			'type' => 'radio',
//			'instructions' => '',
//			'required' => 0,
//			'conditional_logic' => array(
//				array(
//					array(
//						'field' => 'field_5e71b5d030ff4',
//						'operator' => '==',
//						'value' => 'Liposuction',
//					),
//				),
//			),
//			'wrapper' => array(
//				'width' => '',
//				'class' => '',
//				'id' => '',
//			),
//			'choices' => array(
//				'Upper Extremities' => 'Upper Extremities',
//				'Torso' => 'Torso',
//				'Lower Extremities' => 'Lower Extremities',
//			),
//			'allow_null' => 0,
//			'other_choice' => 0,
//			'default_value' => '',
//			'layout' => 'vertical',
//			'return_format' => 'value',
//			'save_other_choice' => 0,
//		),
//		array(
//			'key' => 'field_5e7d714c6529e',
//			'label' => 'Measurement Before',
//			'name' => 'liposuction_measurement_before',
//			'type' => 'text',
//			'instructions' => '',
//			'required' => 0,
//			'conditional_logic' => array(
//				array(
//					array(
//						'field' => 'field_5e71b5d030ff4',
//						'operator' => '==',
//						'value' => 'Liposuction',
//					),
//				),
//			),
//			'wrapper' => array(
//				'width' => '',
//				'class' => '',
//				'id' => '',
//			),
//			'default_value' => '',
//			'placeholder' => '',
//			'prepend' => '',
//			'append' => '',
//			'maxlength' => '',
//		),
//		array(
//			'key' => 'field_5e7d71696529f',
//			'label' => 'Measurement After',
//			'name' => 'liposuction_measurement_after',
//			'type' => 'text',
//			'instructions' => '',
//			'required' => 0,
//			'conditional_logic' => array(
//				array(
//					array(
//						'field' => 'field_5e71b5d030ff4',
//						'operator' => '==',
//						'value' => 'Liposuction',
//					),
//				),
//			),
//			'wrapper' => array(
//				'width' => '',
//				'class' => '',
//				'id' => '',
//			),
//			'default_value' => '',
//			'placeholder' => '',
//			'prepend' => '',
//			'append' => '',
//			'maxlength' => '',
//		),
//		array(
//			'key' => 'field_5e7d719680962',
//			'label' => 'Implant type',
//			'name' => 'breast_augmentation_implant_type',
//			'type' => 'radio',
//			'instructions' => '',
//			'required' => 0,
//			'conditional_logic' => array(
//				array(
//					array(
//						'field' => 'field_5e71b5d030ff4',
//						'operator' => '==',
//						'value' => 'Breast Augmentation',
//					),
//				),
//			),
//			'wrapper' => array(
//				'width' => '',
//				'class' => '',
//				'id' => '',
//			),
//			'choices' => array(
//				'Saline' => 'Saline',
//				'SIlicone' => 'SIlicone',
//			),
//			'allow_null' => 0,
//			'other_choice' => 0,
//			'default_value' => '',
//			'layout' => 'vertical',
//			'return_format' => 'value',
//			'save_other_choice' => 0,
//		),
//		array(
//			'key' => 'field_5e7d71e280963',
//			'label' => 'Cup Size Pre-OP',
//			'name' => 'breast_augmentation_cup_size_pre-op',
//			'type' => 'radio',
//			'instructions' => '',
//			'required' => 0,
//			'conditional_logic' => array(
//				array(
//					array(
//						'field' => 'field_5e71b5d030ff4',
//						'operator' => '==',
//						'value' => 'Breast Augmentation',
//					),
//				),
//			),
//			'wrapper' => array(
//				'width' => '',
//				'class' => '',
//				'id' => '',
//			),
//			'choices' => array(
//				'CUP A' => 'CUP A',
//				'CUP B' => 'CUP B',
//				'CUP C' => 'CUP C',
//				'CUP DD/E' => 'CUP DD/E',
//			),
//			'allow_null' => 0,
//			'other_choice' => 0,
//			'default_value' => '',
//			'layout' => 'vertical',
//			'return_format' => 'value',
//			'save_other_choice' => 0,
//		),
//		array(
//			'key' => 'field_5e7d720080964',
//			'label' => 'Cup Size Post-OP',
//			'name' => 'breast_augmentation_cup_size_post-op',
//			'type' => 'radio',
//			'instructions' => '',
//			'required' => 0,
//			'conditional_logic' => array(
//				array(
//					array(
//						'field' => 'field_5e71b5d030ff4',
//						'operator' => '==',
//						'value' => 'Breast Augmentation',
//					),
//				),
//			),
//			'wrapper' => array(
//				'width' => '',
//				'class' => '',
//				'id' => '',
//			),
//			'choices' => array(
//				'CUP A' => 'CUP A',
//				'CUP B' => 'CUP B',
//				'CUP C' => 'CUP C',
//				'CUP DD/E' => 'CUP DD/E',
//			),
//			'allow_null' => 0,
//			'other_choice' => 0,
//			'default_value' => '',
//			'layout' => 'vertical',
//			'return_format' => 'value',
//			'save_other_choice' => 0,
//		),
//		array(
//			'key' => 'field_5e7d721480965',
//			'label' => 'Implant Size in ML',
//			'name' => 'breast_augmentation_implant_size_in_ml',
//			'type' => 'radio',
//			'instructions' => '',
//			'required' => 0,
//			'conditional_logic' => array(
//				array(
//					array(
//						'field' => 'field_5e71b5d030ff4',
//						'operator' => '==',
//						'value' => 'Breast Augmentation',
//					),
//				),
//			),
//			'wrapper' => array(
//				'width' => '',
//				'class' => '',
//				'id' => '',
//			),
//			'choices' => array(
//				'50 ML' => '50 ML',
//				'100 ML' => '100 ML',
//				'150 ML' => '150 ML',
//				'200 ML' => '200 ML',
//			),
//			'allow_null' => 0,
//			'other_choice' => 0,
//			'default_value' => '',
//			'layout' => 'vertical',
//			'return_format' => 'value',
//			'save_other_choice' => 0,
//		),
//	),
//	'location' => array(
//		array(
//			array(
//				'param' => 'post_type',
//				'operator' => '==',
//				'value' => 'gallery',
//			),
//		),
//	),
//	'menu_order' => 0,
//	'position' => 'normal',
//	'style' => 'default',
//	'label_placement' => 'top',
//	'instruction_placement' => 'label',
//	'hide_on_screen' => '',
//	'active' => true,
//	'description' => '',
//));
//
//endif;
//?>